### ISSUE TITLE
unable to send direct messages

### ISSUE THREAD

**Issue by neuwirthe** [ropensci/rtweet#735]
`rtweet` 1.0.2
`R` 4.2.1
`MacOS` 12.5.1
I created a new twitter app with all the keys needed on `developer.twitter.com`
I set app permissions to 
`Read and Write and Direct message`
But I am unable to send direct messages.
I get
 
```
Error: Twitter API failed [400]
Check error message at https://developer.twitter.com/en/support/twitter-api/error-troubleshooting
```
I used 

```{r}
rtweet_bot(
  api_key = Sys.getenv("RTWEET_API_KEY"),
  api_secret = Sys.getenv("RTWEET_API_SECRET"),
  access_token =  Sys.getenv("RTWEET_ACCESS"),
  access_secret =  Sys.getenv("RTWEET_ACCESS_SECRET")
) ->
  auth_bot

auth_save(auth_bot,"R_with_rtweet")
```
and

```{r}
auth_as(auth_bot)
```

```
post_tweet("This is an rtweet test")
```

works, but sends a public tweet, which is annoying when doing tests

```
post_message("This is an rtweet test", "neuwirthe")
```

does not work.

I cannot send a complete reprex because that would imply sending keys and secrets.

How can I make direct messages work?

<img width="557" alt="2022-09-12_00-31-42" src="https://user-images.githubusercontent.com/157619/189551835-9bb36843-2008-4ee4-b328-f1c976913cd3.png">

**Comment by llrs** [comment]
I think the problem is that you are trying to send a message to yourself and this is not allowed in Twitter. Try sending a direct message to someone else

**Comment by neuwirthe** [comment]
I create a new account which can receive direct messages from everybody.
I still get the error message.

**Comment by llrs** [comment]
Mmh, this time when I tried the code I got a warning which might indicate something is indeed wrong:

```r
In addition: Warning message:
Unknown or uninitialised column: `user_id`. 
```

I will look to it with more detail. Thanks for the report.

**Comment by llrs** [comment]
Sorry, there was indeed a bug in the `post_message`. It should be fixed now on the devel branch.

**Comment by neuwirthe** [comment]
I installed the Level version from GitHub and still get

```
post_message("test with rtweet", "gabineuw")
```

Error: Twitter API failed [400]
Check error message at https://developer.twitter.com/en/support/twitter-api/error-troubleshooting

**Comment by llrs** [comment]
Did you install it from the devel branch?

**Comment by llrs** [comment]
In github there are several branches, if you didn't specify the devel branch you installed the default which doesn't have the fix. Did you install with something like `remotes::install_github("ropensci/rtweet@devel")`? Could you show the output of your `packageVersion("rtweet")` ? This would help me find which rtweet version have you installed.

**Comment by neuwirthe** [comment]
My fault.
With the Level version from GitHub, things work fine.


Thank you

Erich
